# To create values use: `echo -n 'secret-value' | base64` - and paste it under the data
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: ~
type: Opaque
data:
  mongo_db: ~
  mongo_user: ~
  mongo_password: ~
  mongo_host: ~
  jwt_secret: ~
  cookie_password: ~
  admin_email: ~
  admin_password: ~
  mailer_host: ~
  mailer_port: ~
  mailer_user: ~
  mailer_password: ~
  mailer_secure: ~
  sentry_dsn: ~
